### ISSUE TITLE
Add check for low disk space

### ISSUE THREAD

**Issue by TwoLeggedCat** [PaperMC/Paperclip#37]
The number of reports of server owners running out of disk space on small VPSs and such while the server is running is disconcertingly high, and a simple feature to check available disk space on launch would have virtually no downside, especially if made configurable through a startup flag.

While this is out-of-scope with the majority of the project, it could save a lot of people from the above situation. I would have PR'd this rather than open an issue, but I am seeking input as to whether or not this feature should be included at all.

**Comment by Malfrador** [comment]
Im not against adding this, but im wondering how many of the people that do not regularly check their disk space would actually read the startup log. There is already the problem that quite a lot of people did not read the Java Version warning, and I would expect even less people to read the disk space warning.

**Comment by TwoLeggedCat** [comment]
> Im not against adding this, but im wondering how many of the people that do not regularly check their disk space would actually read the startup log. There is already the problem that quite a lot of people did not read the Java Version warning, and I would expect even less people to read the disk space warning, so it might not be very useful in the end as the target audience does not read log files anyways.

While you have a very valid point, however the warning for Java 11 worked quite well and I'm inclined to believe more people would have read/listened to the Java 16 warning had there not just been one for Java 11.

Another concern is that, this being in Paperclip, the message would likely be thrown very early, before all the configuration files are dumped to the console, covering it very quickly.

I assume that the developers would be against putting it in the server itself, however, if permitted, this could not only be thrown later without something like a 10 second delay before logging, but also read a config from `paper.yml` to see if the warning is disabled.

**Comment by electronicboy** [comment]
The warning for java 11 comes stupidly late in the startup process so that it can be read, delaying this to appear at a useful time is also not something paperclip can do, paper.yml is also irrelevant and not something paperclip can read either

This also wouldn't really cover any useful places FOR this, e.g. many issues occur while the server is actually running, not during startup, this would not appear in log files either; I think that this feature is entirely out of bounds for the goal here and really would be better off dealt with with a script or some cron tasks or something such as a proper monitoring setup so that people can actually monitor what is going on and take steps to protect the server
